name: Line Works Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 毎1時間ごとに実行

env:
  WORKS_ID: ${{ secrets.WORKS_ID }}
  WORKS_PASSWORD: ${{ secrets.WORKS_PASSWORD }}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create log directory
        run: mkdir -p log

      - name: Send notification (正常)
        if: ${{ success() }}
        run: |
          python src/notify.py "ワークフローが正常に実行開始されました"
        env:
          WORKS_ID: ${{ secrets.WORKS_ID }}
          WORKS_PASSWORD: ${{ secrets.WORKS_PASSWORD }}

      - name: Run bot
        run: python src/main.py
        id: bot_run

      - name: Send notification (エラー)
        if: ${{ failure() }}
        run: |
          python src/notify.py "エラーが発生しました: ${{ steps.bot_run.outcome }}"
        env:
          WORKS_ID: ${{ secrets.WORKS_ID }}
          WORKS_PASSWORD: ${{ secrets.WORKS_PASSWORD }}
